[package]
name = "merovingian"
version = "0.1.0"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]

[dependencies]
bincode = "1.0"
lazy_static = "1.0"
maplit = "1.0"
serde = "1.0"
serde_derive = "1.0"
structopt = { version = "0.2", default-features = false }
